# Generated by Django 3.2.7 on 2021-11-09 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('password_hash', models.CharField(max_length=1000)),
                ('current_auth_token', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proposals.account'),
            preserve_default=False,
        ),
    ]
