# Generated by Django 3.2.7 on 2021-11-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_auto_20211109_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='account',
            name='current_auth_token',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
