# Generated by Django 3.2.7 on 2021-11-16 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_alter_account_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(default=False)),
                ('proposal_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proposals.proposal')),
                ('voter_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proposals.account')),
            ],
        ),
        migrations.AddConstraint(
            model_name='proposalvote',
            constraint=models.UniqueConstraint(fields=('voter_id', 'proposal_id'), name='One User One Vote'),
        ),
    ]
