# Generated by Django 3.2.7 on 2021-11-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_auto_20211116_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='no_votes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='yes_votes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
