# Generated by Django 3.2.7 on 2021-11-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_auto_20211116_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='no_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='yes_votes',
            field=models.IntegerField(default=0),
        ),
    ]
